### PR TITLE
CompletedAssigment

### PR DESCRIPTION
**Pull request by niginaBerdieva**
Finished all, could make this framework more beauty by using Cucumber, but didn't have enough time.

### CODE REVIEW

**Comment by hbahuguna2** [comment]
There are some formatting issues, tear down is not provided, dragDrop assertion is not present, openInNewTab test is not switching to new tab, TODO on javaScriptAlerts. Please address these and any other issues and resubmit.

**Comment by niginaBerdieva** [comment]
ok let me check. There was a lot of work )

**Comment by niginaBerdieva** [comment]
For some reason drag and drop not working, so  I can not assert it.

**Comment by niginaBerdieva** [comment]
others requirements I fixed

**Pull request closed without merging**
