### PR TITLE
Exercise Submitted

### PR DESCRIPTION
**Pull request by Parvathi-724**
Please review and provide your feedback

### CODE REVIEW

**Comment by hbahuguna2** [comment]
Hi, I'm getting the following compilation errors with your submission:

image

Please fix these errors and resubmit the PR. 
Thanks!

**Comment by Parvathi-724** [comment]
> Hi, I'm getting the following compilation errors with your submission:
> 
> image
> 
> Please fix these errors and resubmit the PR.
> Thanks!

Hi, It was working  in my local. I think I missed some files to upload. I will look into it, then will resubmit the PR.

**Comment by Parvathi-724** [comment]
image

**Comment by hbahuguna2** [comment]
I'm now getting NullPointer Error while running tests on my IDE:

image

**Comment by Parvathi-724** [comment]
Hi .. The code is working in my local ,that might be issue to your local environment ?  I am little curious to know what are next steps in this process .

**Comment by hbahuguna2** [comment]
> Hi .. The code is working in my local ,that might be issue to your local environment ? I am little curious to know what are next steps in this process .

I'm pretty sure this is not an issue with my local but with the submission itself. Usually we expect that as soon as we clone the project we are able to build it. Next we should be able to run tests without any change in code or configuration on my side. Then only we look at the code. So the next step is to test that the submission really work on a different computer.

**Pull request closed without merging**
