### PR TITLE
MirRakibHossain- 14-09

### PR DESCRIPTION
**Pull request by WSRakib**
Take home Assessment. 
From Mir Rakib Hossain

### CODE REVIEW

**Comment by hbahuguna2** [comment]
dragAndDrop, dropDown, dynamicContent, dynamicControls, fileDownload, iFrame, jsError assertions are missing.

**Comment by WSRakib** [comment]
> dragAndDrop, dropDown, dynamicContent, dynamicControls, fileDownload, iFrame, jsError assertions are missing.

Thank you for taking your time to see my code. 
i believe all the test are there, that you are looking for. It started from line 99 in my Test Class. 
Please see the attached link for my G-Drive for the screenshot. Thank you. 
https://drive.google.com/file/d/1P6xK40CTZ7eN8DGl0-oHALJH6dofiHsz/view?usp=sharing

**Comment by hbahuguna2** [comment]
> > dragAndDrop, dropDown, dynamicContent, dynamicControls, fileDownload, iFrame, jsError assertions are missing.
> 
> Thank you for taking your time to see my code.
> i believe all the test are there, that you are looking for. It started from line 99 in my Test Class.
> Please see the attached link for my G-Drive for the screenshot. Thank you.
> https://drive.google.com/file/d/1P6xK40CTZ7eN8DGl0-oHALJH6dofiHsz/view?usp=sharing

Tests are there but actual assertions are missing.

**Comment by WSRakib** [comment]
Please check my code for all the missing quote. thank you

**Pull request closed without merging**
