### PR TITLE
Adding Files for DotDash take home Selenium tests

### PR DESCRIPTION
**Pull request by kalebhushan**
Author: Bhushan Kale

### CODE REVIEW

**Comment by kalebhushan** [comment]
Please note that drag and drop test does not work in spite of using the correct dragAndDropaction. I tried a couple of work arounds but need more investigation.

**Comment by hbahuguna2** [comment]
> Please note that drag and drop test does not work in spite of using the correct dragAndDropaction. I tried a couple of work arounds but need more investigation.

I'm getting this compilation error on the project
```[ERROR] take-home-webdriver-test/src/test/java/pages/FilePage.java:[12,24] package javax.activation does not exist```
This pkg is not being used anywhere but there is still reference to it in the code so it's throwing a compilation error. IMO the candidate should make sure that there are no compilation errors before submitting.


I tried to remove that line in the code to fix the compilation error and rebuilt the project. Now I'm getting `java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "driver" is null`  for all tests.

**Comment by kalebhushan** [comment]
> > Please note that drag and drop test does not work in spite of using the correct dragAndDropaction. I tried a couple of work arounds but need more investigation.
> 
> I'm getting this compilation error on the project
> `[ERROR] take-home-webdriver-test/src/test/java/pages/FilePage.java:[12,24] package javax.activation does not exist`
> This pkg is not being used anywhere but there is still reference to it in the code so it's throwing a compilation error. IMO the candidate should make sure that there are no compilation errors before submitting.
> 
> I tried to remove that line in the code to fix the compilation error and rebuilt the project. Now I'm getting `java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "driver" is null` for all tests.

Oh I did not get those errors I could run all tests. I can fix these issues if you would like.

**Comment by kalebhushan** [comment]
Do you have your maven configured btw? Could you do a clean install before running tests? Also which Java are you on?

**Comment by hbahuguna2** [comment]
> > > Please note that drag and drop test does not work in spite of using the correct dragAndDropaction. I tried a couple of work arounds but need more investigation.
> > 
> > 
> > I'm getting this compilation error on the project
> > `[ERROR] take-home-webdriver-test/src/test/java/pages/FilePage.java:[12,24] package javax.activation does not exist`
> > This pkg is not being used anywhere but there is still reference to it in the code so it's throwing a compilation error. IMO the candidate should make sure that there are no compilation errors before submitting.
> > I tried to remove that line in the code to fix the compilation error and rebuilt the project. Now I'm getting `java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "driver" is null` for all tests.
> 
> Oh I did not get those errors I could run all tests. I can fix these issues if you would like.

I think you would get the first one which is compilation error. Second one is due to windows chromedriver.exe so it won't work on any other OS.  I just changed the `driverPath` to Mac chromedriver executable on my computer and it seems to work now. Usually we should make sure that the code should work on other OS as well. So same is the case with File Upload. These tests fail for me because Windows specific file paths are used.

**Comment by kalebhushan** [comment]
> I think you would get the first one which is compilation error. Second one is due to windows chromedriver.exe so it won't work on any other OS. I just changed the `driverPath` to Mac chromedriver executable on my computer and it seems to work now. Usually we should make sure that the code should work on other OS as well. So same is the case with File Upload. These tests fail for me because Windows specific file paths are used.

Ah that makes sense. Sorry missed that point. I tested on Windows and I have only one laptop.

**Pull request closed without merging**
